Fixed LIMO-142. Warning when simulating a supply chain.
WARNING [org.netbeans.core.windows.WindowManagerImpl]
java.lang.IllegalStateException: Problem in some module which uses Window System: Window System API is required to be called from AWT thread only